name: Android Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Versi rilis (contoh: 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle 8.5
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/my-release-key.keystore

    - name: Build Signed Release APK
      run: gradle assembleRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: app-signed-release-apk
        path: app/build/outputs/apk/release/*.apk

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        files: app/build/outputs/apk/release/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
